"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .customerupdate import CustomerUpdate, CustomerUpdateTypedDict
from macropay_sdk.types import BaseModel
from macropay_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class CustomersUpdateRequestTypedDict(TypedDict):
    id: str
    r"""The customer ID."""
    customer_update: CustomerUpdateTypedDict


class CustomersUpdateRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The customer ID."""

    customer_update: Annotated[
        CustomerUpdate,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
