"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .missinginvoicebillingdetails import MissingInvoiceBillingDetailsData
from .notpaidorder import NotPaidOrderData
from dataclasses import dataclass, field
import httpx
from macropay_sdk.models import MacropayError
from macropay_sdk.types import BaseModel
from macropay_sdk.utils import FieldMetadata, PathParamMetadata, SecurityMetadata
from typing import Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class CustomerPortalOrdersGenerateInvoiceSecurityTypedDict(TypedDict):
    customer_session: NotRequired[str]
    member_session: NotRequired[str]


class CustomerPortalOrdersGenerateInvoiceSecurity(BaseModel):
    customer_session: Annotated[
        Optional[str],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="http",
                sub_type="bearer",
                field_name="Authorization",
            )
        ),
    ] = None

    member_session: Annotated[
        Optional[str],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="http",
                sub_type="bearer",
                field_name="Authorization",
            )
        ),
    ] = None


class CustomerPortalOrdersGenerateInvoiceRequestTypedDict(TypedDict):
    id: str
    r"""The order ID."""


class CustomerPortalOrdersGenerateInvoiceRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The order ID."""


CustomerPortalOrdersGenerateInvoiceResponse422CustomerPortalOrdersGenerateInvoiceUnion = TypeAliasType(
    "CustomerPortalOrdersGenerateInvoiceResponse422CustomerPortalOrdersGenerateInvoiceUnion",
    Union[MissingInvoiceBillingDetailsData, NotPaidOrderData],
)
r"""Order is not paid or is missing billing name or address."""


@dataclass(unsafe_hash=True)
class CustomerPortalOrdersGenerateInvoiceResponse422CustomerPortalOrdersGenerateInvoice(
    MacropayError
):
    r"""Order is not paid or is missing billing name or address."""

    data: CustomerPortalOrdersGenerateInvoiceResponse422CustomerPortalOrdersGenerateInvoiceUnion = field(
        hash=False
    )

    def __init__(
        self,
        data: CustomerPortalOrdersGenerateInvoiceResponse422CustomerPortalOrdersGenerateInvoiceUnion,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
