"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .customfieldupdate import CustomFieldUpdate, CustomFieldUpdateTypedDict
from macropay_sdk.types import BaseModel
from macropay_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class CustomFieldsUpdateRequestTypedDict(TypedDict):
    id: str
    r"""The custom field ID."""
    custom_field_update: CustomFieldUpdateTypedDict


class CustomFieldsUpdateRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The custom field ID."""

    custom_field_update: Annotated[
        CustomFieldUpdate,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
