"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .eventtypeupdate import EventTypeUpdate, EventTypeUpdateTypedDict
from macropay_sdk.types import BaseModel
from macropay_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class EventTypesUpdateRequestTypedDict(TypedDict):
    id: str
    r"""The event type ID."""
    event_type_update: EventTypeUpdateTypedDict


class EventTypesUpdateRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The event type ID."""

    event_type_update: Annotated[
        EventTypeUpdate,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
