"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from macropay_sdk.types import BaseModel
from macropay_sdk.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class Oauth2ClientsOauth2GetClientRequestTypedDict(TypedDict):
    client_id: str


class Oauth2ClientsOauth2GetClientRequest(BaseModel):
    client_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
