"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .orderupdate import OrderUpdate, OrderUpdateTypedDict
from macropay_sdk.types import BaseModel
from macropay_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class OrdersUpdateRequestTypedDict(TypedDict):
    id: str
    r"""The order ID."""
    order_update: OrderUpdateTypedDict


class OrdersUpdateRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The order ID."""

    order_update: Annotated[
        OrderUpdate,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
