"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .productbenefitsupdate import ProductBenefitsUpdate, ProductBenefitsUpdateTypedDict
from macropay_sdk.types import BaseModel
from macropay_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class ProductsUpdateBenefitsRequestTypedDict(TypedDict):
    id: str
    product_benefits_update: ProductBenefitsUpdateTypedDict


class ProductsUpdateBenefitsRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    product_benefits_update: Annotated[
        ProductBenefitsUpdate,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
