"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class SubscriptionStatus(str, Enum):
    INCOMPLETE = "incomplete"
    INCOMPLETE_EXPIRED = "incomplete_expired"
    TRIALING = "trialing"
    ACTIVE = "active"
    PAST_DUE = "past_due"
    CANCELED = "canceled"
    UNPAID = "unpaid"
    # Added by hand: the generated enum predates these values and a
    # str Enum is closed, so a missing value makes the SDK reject a
    # valid API response outright. Kept in sync with the OpenAPI spec.
    PAUSED = "paused"
