"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .organization import Organization, OrganizationTypedDict
from datetime import datetime
from macropay_sdk.types import BaseModel
from macropay_sdk.utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Literal
from typing_extensions import Annotated, TypedDict


class WebhookOrganizationUpdatedPayloadTypedDict(TypedDict):
    r"""Sent when a organization is updated.

    **Discord & Slack support:** Basic
    """

    timestamp: datetime
    data: OrganizationTypedDict
    type: Literal["organization.updated"]


class WebhookOrganizationUpdatedPayload(BaseModel):
    r"""Sent when a organization is updated.

    **Discord & Slack support:** Basic
    """

    timestamp: datetime

    data: Organization

    TYPE: Annotated[
        Annotated[
            Literal["organization.updated"],
            AfterValidator(validate_const("organization.updated")),
        ],
        pydantic.Field(alias="type"),
    ] = "organization.updated"
