"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from macropay_sdk.types import BaseModel
from macropay_sdk.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class WebhooksRedeliverWebhookEventRequestTypedDict(TypedDict):
    id: str
    r"""The webhook event ID."""


class WebhooksRedeliverWebhookEventRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The webhook event ID."""
