"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import importlib.metadata

__title__: str = "macropay-sdk"
__version__: str = "3.0.6"
__openapi_doc_version__: str = "0.1.0"
__gen_version__: str = "2.737.0"
__user_agent__: str = "speakeasy-sdk/python 3.0.6 2.737.0 0.1.0 macropay-sdk"

try:
    if __package__ is not None:
        __version__ = importlib.metadata.version(__package__)
except importlib.metadata.PackageNotFoundError:
    pass
